---
namespace: open-cluster-management

resources:
- ./manifests
- olm_addon_controller.yaml


images:
  - name: quay.io/fgiloux/olm-addon-controller
    newName: quay.io/fgiloux/olm-addon-controller
    newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
