---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: olm-addon-controller
  labels:
    app: olm-addon-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: olm-addon-controller
  template:
    metadata:
      labels:
        app: olm-addon-controller
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: olm-addon-sa
      containers:
      - name: olm-addon-controller
        image: quay.io/fgiloux/olm-addon-controller
        imagePullPolicy: Always
        args:
          - -v=1
        securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ "ALL" ]