apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: non-openshift
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
          - key: vendor
            operator: NotIn
            values:
            - OpenShift
